### ISSUE TITLE
Security issue?

### ISSUE THREAD

**Issue by jbwhit** [pydata/pandas-design#13]
Please close if not relevant, but I'm not sure that you want this file: 

https://github.com/pydata/pandas-design/blob/master/github_deploy_key.enc

committed publicly.

**Comment by shoyer** [comment]
cc @jorisvandenbossche

**Comment by wesm** [comment]
I don't know the inner workings of GH deploy keys but the doctr docs suggest that this is safe to do

**Comment by jorisvandenbossche** [comment]
Yes, no expert as well, but I followed the instructions of doctr, and it is the encrypted key, the public one I didn't commit. @jbwhit If you think this is a problem (or maybe should be explained in there docs if it isn't), maybe bring it up at https://github.com/drdoctr/doctr/issues
